// <auto-generated />
namespace Phonix.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Propetychange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Propetychange));
        
        string IMigrationMetadata.Id
        {
            get { return "201902260603168_Propety-change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
